# This is a config for E2B sandbox template.
# You can use template ID (rwcjty3x4s2b4umh57a1) or template name (vibe-codexa-123-code-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-codexa-123-code-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-codexa-123-code-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-codexa-123-code-2')

team_id = "ee7e0cb8-36b8-4f50-ac8a-e72a2090b78d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-codexa-123-code-2"
template_id = "rwcjty3x4s2b4umh57a1"
